/**
 * SSM Agent Node Type Definitions
 *
 * State-Space Models (SSMs) like Mamba provide linear-time sequence
 * processing, ideal for continuous monitoring of event streams.
 *
 * Key advantages over Transformers:
 * - Linear O(n) complexity vs quadratic O(n²)
 * - 4-5x faster inference
 * - Fixed-size state (ideal for continuous monitoring)
 * - Lower memory usage (no attention matrix/KV cache)
 *
 * Use cases: Email inbox monitoring, security log analysis,
 * activity stream classification, anomaly detection.
 */

// ============================================================================
// MODEL PROVIDERS
// ============================================================================

/**
 * Supported SSM model providers
 * Self-hosted options (Ollama, vLLM) are prioritized for cost efficiency
 */
export type SSMModelProvider = 'ollama' | 'vllm' | 'huggingface' | 'replicate';

// ============================================================================
// MONITORING CONFIGURATION
// ============================================================================

/**
 * Types of monitoring the SSM can perform
 */
export type SSMMonitoringType =
  | 'security_threat'      // Detect potential security threats in logs
  | 'anomaly_detection'    // Identify unusual patterns in data streams
  | 'classification'       // Categorize incoming events
  | 'summarization'        // Summarize activity streams
  | 'custom';              // User-defined monitoring logic

/**
 * How the SSM receives events to monitor
 */
export type SSMEventSourceType =
  | 'webhook'   // Events pushed via webhook
  | 'polling'   // Periodically fetch events from a source
  | 'pubsub'    // Subscribe to Pub/Sub topic (Google Cloud, etc.)
  | 'manual';   // Events triggered manually or from canvas connections

/**
 * Output format for SSM responses
 */
export type SSMOutputFormat =
  | 'alert'          // Structured alert object
  | 'summary'        // Natural language summary
  | 'classification' // Single classification label
  | 'raw';           // Raw JSON response

/**
 * Severity levels for alerts
 */
export type SSMAlertSeverity = 'low' | 'medium' | 'high' | 'critical';

// ============================================================================
// NODE CONFIGURATION
// ============================================================================

/**
 * SSM Agent Node Configuration
 * Defines all settings for an SSM-based monitoring node
 */
export interface SSMAgentNodeConfig {
  // Identity
  name: string;
  description: string;

  // Model Configuration
  model_provider: SSMModelProvider;
  model_name: string;
  model_endpoint?: string; // For self-hosted (Ollama URL, vLLM endpoint)

  // Event Source
  event_source_type: SSMEventSourceType;
  polling_source?: 'gmail' | 'slack' | 'custom_api';
  polling_interval_seconds?: number;
  webhook_secret?: string;

  // Monitoring Configuration
  monitoring_type: SSMMonitoringType;
  custom_prompt?: string;          // Custom instructions for monitoring
  alert_threshold?: number;        // 0-1 confidence threshold for alerts

  // Output Configuration
  output_format: SSMOutputFormat;
  alert_webhook?: string;          // External webhook to send alerts to

  // State Management
  state_retention_hours?: number;  // How long to retain SSM state
  checkpoint_enabled?: boolean;    // Enable state checkpointing
}

// ============================================================================
// RUNTIME TYPES
// ============================================================================

/**
 * Alert generated by SSM monitoring
 */
export interface SSMAlert {
  id: string;
  severity: SSMAlertSeverity;
  title: string;
  details: Record<string, unknown>;
  timestamp: string;
  acknowledged: boolean;
  source_node_id?: string;
}

/**
 * SSM execution state for runtime tracking
 */
export interface SSMExecutionState {
  node_id: string;
  status: 'idle' | 'monitoring' | 'paused' | 'error';
  last_event_at?: string;
  events_processed: number;
  alerts_generated: number;
  error_message?: string;
}
